### ISSUE TITLE
[error]can't merge

### ISSUE THREAD

**Issue by yakiebi** [bbc-mc/sdweb-merge-block-weighted-gui#11]
#### Merge Block Weighted ####
model_0    : BloodOrangeMix-pruned.ckpt [9a79d11c]
model_1    : instagram-latest-plus-clip-v6e1_50000_0-f222_1-Add_difference-merged.ckpt [c52c7d69]
base_alpha : 0
output_file: C:\lezgo\stable-diffusion-webui\models\Stable-diffusion\NewBloodOrange.ckpt
weights    : 1,0.9,0.7,0.5,0.3,0.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.1,0.3,0.5,0.7,0.9,1
loading BloodOrangeMix-pruned.ckpt [9a79d11c]
Traceback (most recent call last):
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\lezgo\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\lezgo\stable-diffusion-webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\ui_mbw.py", line 135, in onclick_btn_do_merge_block_weighted
    result, ret_message = merge(weights=_weights, model_0=model_A, model_1=model_B, allow_overwrite=chk_allow_overwrite, base_alpha=sl_base_alpha, output_file=_output, verbose=chk_verbose_mbw)
  File "C:\lezgo\stable-diffusion-webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\merge_block_weighted.py", line 48, in merge
    theta_0 = load_model(model_0, device)
  File "C:\lezgo\stable-diffusion-webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\merge_block_weighted.py", line 45, in load_model
    return sd_models.read_state_dict(model_file, map_location=_device)
AttributeError: module 'modules.sd_models' has no attribute 'read_state_dict'

I got this error when trying to merge model and i don't have a clue of what's going on here.
sry for being a computer noob （;´д｀）

**Comment by bbc-mc** [comment]
Hi thanks for report.
I see your log, and found this row,
`AttributeError: module 'modules.sd_models' has no attribute 'read_state_dict'`

This error says 'modules.sd_models' not found, but they MUST exist because there are core file of AUTO1111.
So I doubt cache of python.

Would you try steps below?
1. stop your webui
2. go to Extension directory
- from your log, `C:\lezgo\stable-diffusion-webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\`
3. delete `__pycache__` directory
- `__pycache__` is generated by python automatically, and store old data to speed up things, but sometimes cause problem.
- this directory will be re-generated by python at start.
5. restart webui, and try

**Comment by bbc-mc** [comment]
Im happy to hear you solve that !
