### ISSUE TITLE
Error occurs after processing is complete (not recorded in history.tsv)

### ISSUE THREAD

**Issue by acncagua** [bbc-mc/sdweb-merge-block-weighted-gui#15]
After MBW is used, files are generated.
However, an error occurs.
history.tsv is not updated
1111 is the latest (4d158c1879bcc88dad1211cad900b927bfcfb819)

```
#### Merge Block Weighted ####
  model_0    : AnyV3-nai-sfw_add03-wd135_sum03-gape_add10.safetensors
  model_1    : zmodels_0_marge_source/insta-f222-v15_add10.safetensors
  base_alpha : 0
  output_file: /home/username/stable-diffusion-webui/models/Stable-diffusion/AnyV3-nai-sfw_add03-wd135_sum03-gape_add10-insta-f222-v15_add10_MBW.safetensors
  weights    : 1,0.9,0.7,0.5,0.3,0.1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.1,0.3,0.5,0.7,0.9,1
  skip ids   : 0 : 0:None, 1:Skip, 2:Reset
loading AnyV3-nai-sfw_add03-wd135_sum03-gape_add10.safetensors
loading zmodels_0_marge_source/insta-f222-v15_add10.safetensors
  merging ...
Stage 1/2:   0%|                                                                               | 0/1819 [00:00<?, ?it/s]cond_stage_model.transformer.text_model.embeddings.position_ids
  modelA: 'position_ids' key found. do nothing : 0: dtype:torch.int64
Stage 1/2: 100%|████████████████████████████████████████████████████████████████████| 1819/1819 [00:36<00:00, 49.88it/s]
Stage 2/2: 100%|███████████████████████████████████████████████████████████████| 1133/1133 [00:00<00:00, 2621150.82it/s]
Saving...
Done!
merged.
Traceback (most recent call last):
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/username/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/username/stable-diffusion-webui/extensions/sdweb-merge-block-weighted-gui/scripts/mbw/ui_mbw.py", line 195, in onclick_btn_do_merge_block_weighted
    mergeHistory.add_history(model_A, model_B, model_O, model_O_hash, sl_base_alpha, _weights, "", weight_name)
  File "/home/username/stable-diffusion-webui/extensions/sdweb-merge-block-weighted-gui/scripts/mbw_util/merge_history.py", line 26, in add_history
    "model_A_hash": f"{model_A.split(' ')[1]}",
IndexError: list index out of range
```

**Comment by bbc-mc** [comment]
Hi, thank you for report.

As your error code, this is related to 'CheckpointInfo'.
'CheckpointInfo' is new class introduced by [recent commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a95f1353089bdeaccd7c266b40cdd79efedfe632) to handle model information.
Extensions are effected by this change which use this information object, including mine.

I'll fix that.

**Comment by ljleb** [comment]
Hey just looking for more info on this, does merging with a model that does not have the `position_ids` key affect the resulting merge in any way? If that's the case, how do I add this key to a model?
