### ISSUE TITLE
error on load in forge newsses version

### ISSUE THREAD

**Issue by kalle07** [bbc-mc/sdweb-merge-block-weighted-gui#40]
*** Error loading script: untitled_ui.py
    Traceback (most recent call last):
      File "E:\WebUI_Forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\WebUI_Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\WebUI_Forge\webui\extensions\sd-webui-untitledmerger\scripts\untitled_ui.py", line 13, in <module>
        from scripts.untitled import merger,misc_util
      File "E:\WebUI_Forge\webui\extensions\sd-webui-untitledmerger\scripts\untitled\merger.py", line 7, in <module>
        import scripts.untitled.misc_util as mutil
      File "E:\WebUI_Forge\webui\extensions\sd-webui-untitledmerger\scripts\untitled\misc_util.py", line 9, in <module>
        networks = script_loading.load_module(os.path.join(paths.extensions_builtin_dir,'Lora','networks.py'))
      File "E:\WebUI_Forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 879, in exec_module
      File "<frozen importlib._bootstrap_external>", line 1016, in get_code
      File "<frozen importlib._bootstrap_external>", line 1073, in get_data
    FileNotFoundError: [Errno 2] No such file or directory: 'E:\\WebUI_Forge\\webui\\extensions-builtin\\Lora\\networks.py'

---
Loading additional modules ... done.

**Comment by kalle07** [comment]
if i want to merge 
error

 model_0    : blackMAGICPONY_v25.safetensors
  model_1    : SDXL_sevenof9_allyouwant.safetensors
  base_alpha : 0.5
  output_file: E:\WebUI_Forge\webui\models\Stable-diffusion\test01.safetensors
  weights    : 1,0.995722430686905,0.982962913144534,0.961939766255643,0.933012701892219,0.896676670145617,0.853553390593274,0.80438071450436,0.75,0.691341716182545,0.62940952255126,0.565263096110026,0.5,0.434736903889974,0.37059047744874,0.308658283817455,0.25,0.195619285495639,0.146446609406726,0.103323329854382,0.0669872981077805,0.0380602337443566,0.0170370868554658,0.00427756931309475,0
  skip ids   : 0 : 0:None, 1:Skip, 2:Reset
loading blackMAGICPONY_v25.safetensors
loading SDXL_sevenof9_allyouwant.safetensors
  merging ...
-- start Stage 1/2 --
Traceback (most recent call last):
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "e:\WebUI_Forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "e:\WebUI_Forge\system\python\lib\site-packages\gradio\utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "E:\WebUI_Forge\webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\ui_mbw.py", line 172, in onclick_btn_do_merge_block_weighted
    result, ret_message = merge(weights=_weights, model_0=model_A, model_1=model_B, allow_overwrite=chk_allow_overwrite,
  File "E:\WebUI_Forge\webui\extensions\sdweb-merge-block-weighted-gui\scripts\mbw\merge_block_weighted.py", line 79, in merge
    for key in (tqdm(theta_0.keys(), desc="Stage 1/2")):
AttributeError: 'NoneType' object has no attribute 'keys'
